### ISSUE TITLE
Synchronization analysis for ILN (ILN : 14182101018)

### ISSUE THREAD

**Issue by NCocman** [louxfaure/sudoc-cloudapp#1]
Bonjour Alexandre,
On a un souci sur notre SUDOC Toolbox, l'analyse de synchro est systématiquement en erreur :
"An error occurred while loading availability:
Http failure response for https://www.sudoc.fr/services/where/1418210118/250548232,241097304,235134066,230459420&format=text/json: 0 Unknown _Error"
Il me semble qu'on avait déjà eu ce problème et que c'est à cause du format json non ?

Et merci pour la nouveauté Copier les PPN ! 

A bientôt
Nicolas

**Comment by louxfaure** [comment]
Salut,
Quelqu'un chez vous a dû modifier la valeur du paramètre ILN. Ici, il est à  1418210118 au lieu de 18.  
https://www.sudoc.fr/services/where/18/250548232,241097304,235134066,230459420&format=text/json:
Va dans les paramètres (petite clef dans la section synchronisation) tu pourras corriger le paramètre.
Merci. Le service copier un ppn vient d'être validé par Exlibris. Je communiquerai  dessus sur la liste dans la soirée.
J'espère que cela vous sera utile.
A+

**Comment by NCocman** [comment]
Merci, ça sent la fausse manip en effet.
Sais tu que l'appli ne sera plus en version Beta ? ;)

**Comment by louxfaure** [comment]
Oui. Il Faut que je change le nom de l'application.
Cela sera pour la prochaine release. J'ai encore quelques idées.
A plus
